In [2]:
%matplotlib qt
import numpy as np
import matplotlib.pyplot as plt
import hyperspy.api as hs
import h5py as hy

In [5]:
hl=hs.load("Ti 0.025 evperc/EELS Spectrum Image (high-loss).dm4")
ll=hs.load('Ti 0.025 evperc\EELS Spectrum Image (low-loss).dm4',signal_type='EELS')

In [6]:
hlc=hs.load('C 0.025 evperc\EELS Spectrum Image (high-loss).dm4',signal_type='EELS')
llc=hs.load('C 0.025 evperc\EELS Spectrum Image (low-loss).dm4',signal_type='EELS')

In [7]:
hl.metadata

├── Acquisition_instrument
│   └── TEM
│       ├── Detector
│       │   └── EELS
│       │       ├── aperture_size = 2.5
│       │       ├── collection_angle = 100.0
│       │       ├── dwell_time = 9.995002498750624
│       │       ├── frame_number = 1
│       │       └── spectrometer = GIF Quantum ER
│       ├── Stage
│       │   ├── tilt_alpha = 0.3
│       │   ├── tilt_beta = 0.0
│       │   ├── x = 0.0045000000000000005
│       │   └── y = 0.0068000000000000005
│       ├── acquisition_mode = STEM
│       ├── beam_current = 0.0
│       ├── beam_energy = 200.0
│       ├── camera_length = 0.0
│       ├── convergence_angle = 0.0
│       ├── magnification = 50000.0
│       └── microscope = HF5000
├── General
│   ├── authors = PM and Jerry
│   ├── date = 2020-03-10
│   ├── original_filename = EELS Spectrum Image (high-loss).dm4
│   ├── time = 14:49:45
│   └── title = EELS Spectrum Image (high-loss)
├── Sample
│   └── description = Titanium oxide
└── Signal
    ├── Noise_properties
    │

In [8]:
hlc.metadata

├── Acquisition_instrument
│   └── TEM
│       ├── Detector
│       │   └── EELS
│       │       ├── aperture_size = 2.5
│       │       ├── collection_angle = 100.0
│       │       ├── dwell_time = 9.995002498750624
│       │       ├── frame_number = 1
│       │       └── spectrometer = GIF Quantum ER
│       ├── Stage
│       │   ├── tilt_alpha = 0.3
│       │   ├── tilt_beta = 0.0
│       │   ├── x = 0.0045000000000000005
│       │   └── y = 0.0068000000000000005
│       ├── acquisition_mode = STEM
│       ├── beam_current = 0.0
│       ├── beam_energy = 200.0
│       ├── camera_length = 0.0
│       ├── convergence_angle = 0.0
│       ├── magnification = 50000.0
│       └── microscope = HF5000
├── General
│   ├── authors = PM and Jerry
│   ├── date = 2020-03-10
│   ├── original_filename = EELS Spectrum Image (high-loss).dm4
│   ├── time = 15:05:49
│   └── title = EELS Spectrum Image (high-loss)
├── Sample
│   └── description = Titanium oxide
└── Signal
    ├── Noise_properties
    │

In [9]:
hlc.plot()
llc.plot()

In [10]:
x=hlc.data>10000 ### allow to remove the gost peak or the noise
hlc.data[x]=0
hlc.plot()

In [11]:
llc.align_zero_loss_peak(also_align=[hlc],calibrate=True)


Initial ZLP position statistics
-------------------------------
Summary statistics
------------------
mean:	-3.54
std:	0.201

min:	-4
Q1:	-3.68
median:	-3.58
Q3:	-3.4
max:	-3.05


In [12]:
hlc

<EELSSpectrum, title: EELS Spectrum Image (high-loss), dimensions: (10, 6|2006)>

In [17]:
hlc=hlc.mean()
llc=llc.mean()
hlc=hlc.rebin([2006/2])
llc=llc.rebin([2006/2])

In [11]:
hlc.plot()
llc.plot()

In [18]:
ll.align_zero_loss_peak(also_align=[hl],calibrate=True)


Initial ZLP position statistics
-------------------------------
Summary statistics
------------------
mean:	0.00583
std:	0

min:	0.00583
Q1:	0.00583
median:	0.00583
Q3:	0.00583
max:	0.00583


In [19]:
ll.plot()
hl.plot()

In [20]:
hl=hl.mean()
ll=ll.mean()

In [15]:
hl

<EELSSpectrum, title: EELS Spectrum Image (high-loss), dimensions: (|1995)>

In [21]:
hl=hl.rebin([1995/2])
ll=ll.rebin([1995/2])

In [22]:
a=hlc.axes_manager["Energy loss"].offset
b=llc.axes_manager["Energy loss"].offset+llc.axes_manager["Energy loss"].scale*llc.axes_manager['Energy loss'].size
c=(a-b)/hlc.axes_manager["Energy loss"].scale
t=np.zeros((llc.axes_manager['Energy loss'].size+hlc.axes_manager['Energy loss'].size+int(c)))

In [23]:
t[0:llc.axes_manager['Energy loss'].size]=llc.data
d=int(llc.axes_manager['Energy loss'].size+c)
t[d:]=hlc.data

In [24]:
t=hs.signals.EELSSpectrum(t)
t.axes_manager[-1].name='Energy loss'
t.axes_manager['Energy loss'].scale=llc.axes_manager["Energy loss"].scale
t.axes_manager['Energy loss'].offset=llc.axes_manager["Energy loss"].offset

In [25]:
t2=t.isig[0.:]
t2.plot()

In [26]:
hlc.plot()

In [27]:
a=hl.axes_manager["Energy loss"].offset
b=ll.axes_manager["Energy loss"].offset+hl.axes_manager["Energy loss"].scale*ll.axes_manager['Energy loss'].size
c=(a-b)/hl.axes_manager["Energy loss"].scale
u=np.zeros((2*ll.axes_manager['Energy loss'].size+int(c)))

In [28]:
u[0:ll.axes_manager['Energy loss'].size]=ll.data
d=int(ll.axes_manager['Energy loss'].size+c)
u[d:]=hl.data

In [29]:
u=hs.signals.EELSSpectrum(u)
u.axes_manager[-1].name='Energy loss'
u.axes_manager['Energy loss'].scale=ll.axes_manager["Energy loss"].scale
u.axes_manager['Energy loss'].offset=ll.axes_manager["Energy loss"].offset

In [30]:
u2=u.isig[0.:]
u2.plot()

In [31]:
a=270
b=310
sigma_peak=t2.isig[float(a):float(b)].valuemax(axis=-1).data
a=round(float(sigma_peak-20))
b=round(float(sigma_peak-10))
p_peak=t2.isig[float(a):float(b)].valuemax(axis=-1).data
offset=285-p_peak
print('max sigma peak =',sigma_peak)
print('max Pi peak =', p_peak)
print('offset =',offset)

max sigma peak = [298.26292111]
max Pi peak = [286.51292094]
offset = [-1.51292094]


In [34]:
m=t2.isig[270.:300.].create_model(auto_background=False)

In [35]:
g1 = hs.model.components1D.Lorentzian()
g2 = hs.model.components1D.Gaussian()
g3 = hs.model.components1D.Gaussian()
m.append(g1)
m.append(g2)
m.append(g3)

In [36]:
m.components.Lorentzian.gamma.value=1
m.components.Lorentzian.centre.value=p_peak
m.components.Lorentzian.A.value=316138.33
m.components.Lorentzian.centre.bmax=p_peak+2
m.components.Lorentzian.centre.bmax=p_peak
m.components.Lorentzian.set_parameters_not_free(parameter_name_list=('gamma'))

m.components.Gaussian.sigma.value=3.55
m.components.Gaussian.centre.value=p_peak+8.16
m.components.Gaussian.A.value=2120075.25
m.components.Gaussian.set_parameters_not_free(parameter_name_list=('sigma','centre'))


m.components.Gaussian_0.sigma.value=1.69
m.components.Gaussian_0.centre.value=p_peak+1.00049573
m.components.Gaussian_0.set_parameters_not_free(parameter_name_list=('sigma','centre'))
# m.components.Gaussian_0.A.bmax=m.components.Lorentzian.A.value/2

C:\ProgramData\Anaconda3\lib\site-packages\hyperspy\component.py:50: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if value == "None" or value == b"None":


In [40]:
m.set_signal_range(284.,296.)# need to be set 

In [41]:
m.fit(bounded=True)

In [42]:
m.plot(True)

In [43]:
x=m.as_signal()
a=float(m.components.Lorentzian.centre.value-3)
b=float(m.components.Lorentzian.centre.value+3)

p_peak=x.isig[a:b].valuemax(axis=-1).data
sigma_peaka=m.components.Gaussian.centre.value
offset=285-p_peak
print('max sigma peak =',sigma_peak)
print('max Pi peak =', p_peak)
print('offset =',offset)

max sigma peak = [298.26292111]
max Pi peak = [286.56292094]
offset = [-1.56292094]


In [44]:
a=(285-t2.axes_manager["Energy loss"].offset)/(p_peak-t2.axes_manager["Energy loss"].offset)
new_scale_c=a*t2.axes_manager["Energy loss"].scale
new_scale_Ti=a*u2.axes_manager["Energy loss"].scale
print(new_scale_c)
print(new_scale_Ti)

[0.04972729]
[0.04972729]


In [45]:
u2.axes_manager["Energy loss"].scale=float(new_scale_Ti)
t2.axes_manager["Energy loss"].scale=float(new_scale_c)

In [46]:
t2.plot()

Après la calibration on recoupe les signaux

In [47]:
hl2=u2.isig[440.:480.]
ll2=u2.isig[0.:40.]
hlc2=t2.isig[270.:310.]
llc2=t2.isig[0.:40.]

In [48]:
hl2.plot()

In [49]:
hl2.remove_background(fast=False)

In [50]:
hlc2.remove_background(fast=False)

In [51]:
hlc3=hlc2.fourier_ratio_deconvolution(ll=llc)
hl3=hl2.fourier_ratio_deconvolution(ll=ll,extrapolate_coreloss=False)

C:\ProgramData\Anaconda3\lib\site-packages\hyperspy\_components\power_law.py:147: RuntimeWarning: invalid value encountered in log
  r = 2 * log(I1 / I2) / log(x2 / x1)


In [315]:
# hl2=hl/np.max(hl().data)

In [52]:
m=hl3.create_model(auto_background=False,auto_add_edges=False)

In [53]:
from math import pi
expression = "(h/p*(arctan((p/w)*(x-e))+p/2))+(h/p*(arctan((p/t)*(x-d))+p/2))"


h2=hl3.isig[476.].data
h1=hl3.isig[453.].data

g3 = hs.model.components1D.Expression(expression=expression,p=pi,w=2,t=2,e=457.5,d=463.0,h=(h2-h1)/2, name="fit")

m.extend([g3])
   
g3.e.free = False
g3.p.free = False
g3.d.free = False
g3.w.free =False
g3.t.free =False
g3.h.free = True


In [56]:
m.set_signal_range(473.,477.)

In [57]:
m.fit(bounded=True)

In [58]:
m.reset_signal_range()

In [59]:
m.plot(True)

In [60]:
x=m.as_signal(component_list=0)

In [55]:
x.plot()

In [61]:
hl4=hl3.data-x
# mask=hl3.data<0
# hl3.data[mask]=0
hl4=hs.signals.EELSSpectrum(hl4)
hl4.metadata=hl3.metadata
hl4.axes_manager=hl3.axes_manager

In [62]:
hl4.plot()

In [63]:
L3=hl4.integrate_in_range(signal_range=(456.5,457.5))
L2=hl4.integrate_in_range(signal_range=(465.25,466.25))

C:\ProgramData\Anaconda3\lib\site-packages\hyperspy\misc\utils.py:1048: VisibleDeprecationWarning: The `Signal1D.integrate_in_range` method is deprecated and will be removed in v2.0. Use a `roi.SpanRoi` followed by `integrate1D` instead.
  warnings.warn(msg, VisibleDeprecationWarning)


In [64]:
L2.data

array([2216246.59069359])

In [65]:
L3.data

array([204589.53557769])

In [66]:
x=L2/L3

In [67]:
x.data

array([10.83264882])

In [68]:
# hlc.sum().save('Super plot\C_TiO3_grain1_plot')

In [69]:
hl5=hl4/np.max(hl4().data)

In [70]:
hs.plot.plot_spectra(hl5)

print(hl5.valuemax(axis=-1).data)

plt.xlabel('Energy Loss (eV)')
plt.ylabel('Norm. Intensity')

plt.axvline(455.8, c='r', ls=':', lw=1)
plt.axvline(456.8, c='r', ls=':', lw=1)
plt.text(x=457., y=.95, s='L3', color='r',fontsize=12)

plt.axvline(465.25, c='r', ls=':', lw=1)
plt.axvline(466.25, c='r', ls=':', lw=1)
plt.text(x=466.45, y=.95, s='L2', color='r',fontsize=12)

[466.18081814]


Text(466.45, 0.95, 'L2')

In [72]:
L2=hl5.integrate_in_range(signal_range=(465.25,466.25))
L2.data

array([18.07148554])